name = "lunchbot4"
main = "build/worker/shim.mjs"
compatibility_date = "2024-11-01"

[build]
command = "cargo install -q \"worker-build@^0.8\" && worker-build --release"

[triggers]
crons = ["0 7 * * mon-fri"]

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "lunchbot4"

[vars]
CF_ACCOUNT_ID = "13da59637f0ecbae107358da500dfb30"
R2_PUBLIC_URL_BASE = "https://pub-ff5be7a6fc124e41bfa8f29ab9cb7264.r2.dev"

[observability.logs]
enabled = true
invocation_logs = true
